import Head from 'next/head'
import Navbar from '../components/Navbar'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

export default function Home() {
   return (
      <>
         <Head>
            <title>Responsive Menu</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <Navbar />
      </>

   )
}
